<?php

/* LES DROITS DU MODULE DE CAISSE */
define('TABLEAU_BORD_CAISSE', 0x01);
define('AJOUTER_ENTREE_CAISSE', 0x02);
define('VOIR_ENTREE_CAISSE',0x04);
define('MODIFIER_ENTREE_CAISSE',0x08);
define('SUPPRIMER_ENTREE_CAISSE',0x10);
define('IMPRIMER_ENTREE_CAISSE',0x20);
define('AJOUTER_SORTIE_CAISSE', 0x40);
define('VOIR_SORTIE_CAISSE',0x80);
define('MODIFIER_SORTIE_CAISSE',0x100);
define('SUPPRIMER_SORTIE_CAISSE',0x200);
define('IMPRIMER_SORTIE_CAISSE',0x400);
define('IMPRIMER_JOURNAL_CAISSE',0x800);
define('ANALYSE_CAISSE',0x1000);
define('IDENTIFICATION_MOTIF_CAISSE',0x2000);
define('VOIR_MODULE_CAISSE',0x4000);
//$voir_module='0x4000';


